export default {
  documents: [],
  documentAuditTrail: {},
  statistics: {},
  documentsByStatus: [],
  document: [],
  doneEditing: null,
  resourceTools: [],
  isOpenModal: false,
  message: null,
  cancel: false,
  isDoneLoading: false,
  isLoading: false,
  isDocLoading: false,
  isToolLoading: false,
};
